export default {
    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',

    REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',

    ADD_MESSAGE_REQUEST: 'ADD_MESSAGE_REQUEST',
    ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',    
    ADD_MESSAGE_ERROR: 'ADD_MESSAGE_ERROR',

    GET_CHAT_LIST_REQUEST: 'GET_CHAT_LIST_REQUEST',
    GET_CHAT_LIST_SUCCESS: 'GET_CHAT_LIST_SUCCESS',
    GET_CHAT_LIST_ERROR: 'GET_CHAT_LIST_ERROR'
}