export default {
    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',

    REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',

    GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST',
    GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
    GET_USER_DATA_ERROR: 'GET_USER_DATA_ERROR',

    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',



    ADD_MESSAGE_REQUEST: 'ADD_MESSAGE_REQUEST',
    ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',    
    ADD_MESSAGE_ERROR: 'ADD_MESSAGE_ERROR',

    GET_CHAT_LIST_REQUEST: 'GET_CHAT_LIST_REQUEST',
    GET_CHAT_LIST_SUCCESS: 'GET_CHAT_LIST_SUCCESS',
    GET_CHAT_LIST_ERROR: 'GET_CHAT_LIST_ERROR',

    GET_CURRENT_CHAT_REQUEST: 'GET_CURRENT_CHAT_REQUEST',
    GET_CURRENT_CHAT_SUCCESS: 'GET_CURRENT_CHAT_SUCCESS',
    GET_CURRENT_CHAT_ERROR:'GET_CURRENT_CHAT_ERROR',
}