POST http://localhost:5000/api/chats/64a2891df2782e643cb6c7dd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDllN2E2NTczYzhlZWRjODU3NjE3OTkiLCJlbWFpbCI6InN1cGVyYXZlbmdlckBtLnNhIiwiaWF0IjoxNjg4OTc3NzQ3LCJleHAiOjE2ODg5ODEzNDd9.iXl2-XTHr3f6Y4pjk2h3Nk_c0e3v7UmeEc8vPNYka_A
Content-Type: application/json

{
    "author": "649e7a6573c8eedc85761799",
    "body": "Hello to all"
}