GET http://localhost:5000/api/chats/all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDllN2E2NTczYzhlZWRjODU3NjE3OTkiLCJlbWFpbCI6InN1cGVyYXZlbmdlckBtLnNhIiwiaWF0IjoxNjg4OTc3NjQxLCJleHAiOjE2ODg5Nzc3MDF9.5xWXzgkg2yCmQL5J8BJ-hsuR8PoA8tSTYdVGR6ZA2Xk