GET http://localhost:5000/api/chats/all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDllN2E2NTczYzhlZWRjODU3NjE3OTkiLCJlbWFpbCI6InN1cGVyYXZlbmdlckBtLnNhIiwiaWF0IjoxNjg4NTM5NzYyLCJleHAiOjE2ODg1Mzk4MjJ9.N7DB-L_jLjFVUeJxEsMtKgDK6I_LiwYnlDepqhkwgQQ