GET http://localhost:5000/api/chats/all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDllN2E2NTczYzhlZWRjODU3NjE3OTkiLCJlbWFpbCI6InN1cGVyYXZlbmdlckBtLnNhIiwiaWF0IjoxNjg4OTc2NTg3LCJleHAiOjE2ODg5NzY2NDd9.VE6U_yKwSncU2OHVDFHf6lK_xB__BZzpVMKC3UFBVPg